---
- hosts: linuxserver
  become: yes
  tasks:   
   - name: i want to install git
     yum: 
      name: git
      state: present

  #  - name: i want to install git
  #    apt: 
  #     name: git
  #     state: present
