---
- hosts: mywebserver
  become: yes
  tasks:
   - name: I want to execute linux command
     command: hostname -f
     register: myvariable
  
   - name: I want to display first task result
     debug:
       msg: "{{myvariable}}"

   - name: install git
     app: 
      name: git
      state: present
     when: myvariable.stdout != "ip-172-31-24-121.ec2.internal"

   - name: install tree
     app: 
      name: tree
      state: present
     when: myvariable.stdout != "ip-172-31-24-121.ec2.internal"

  
