---
- hosts: 172.31.31.211
  become: yes
  tasks:
   - name: I want to execute linux command
     command: hostname -f
     register: myvariable
  
   - name: I want to display first task result
     debug:
       msg: "{{myvariable}}"
