---
- hosts: 172.31.25.33
  become: yes
  tasks:
   - name: install git
     apt: 
      name: git
      stateeeeeeeeeeee: present

   - name: install tree
     apt: 
      name: tree
      state: present

  
