---
- name: configure tomcat admin user
  template:
    src: templates/tomcateuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy tomcate context xml file into ansible node
  template:
    src: templates/tomcatcontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcate host context xml file into ansible node
  template:
    src: templates/tomcathostcontext.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
